app_site_cv/app_site_cv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls'), name='home'),
                  path('', include('skills.urls'), name='skills'),
                  path('', include('contact.urls'), name='contact'),
                  path('', include('etudes.urls'), name='etudes'),
                  path('', include('experience.urls'), name='experiences'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_site_cv/contact/urls.py
from django.urls import path
from contact import views as contact_views
from . import views

app_name = "contact"

urlpatterns = [
    path('contact/', contact_views.contact_view, name='contact'),
    path('succes/', contact_views.contact_view, name='succes'),
]

app_site_cv/etudes/urls.py
from django.urls import path

from . import views

app_name = "etudes"

urlpatterns = [
    path('etudes/', views.etudes, name='etudes'),
]

app_site_cv/experience/urls.py
from django.urls import path

from . import views

app_name = "experiences"

urlpatterns = [
    path('experience', views.experiences_pro, name='experiences'),
    path('creer', views.creer_view, name='creer'),
    path('<slug:slug>/', views.experience_pro, name='experience')
]

app_site_cv/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
]

app_site_cv/skills/urls.py
from django.urls import path

from . import views

app_name = "skills"

urlpatterns = [
    path('skills/', views.skills, name='skills'),
    path('create_skills', views.create_skills, name='create_skills')
]

app_site_cv/contact/models.py
from django.db import models


class Contact(models.Model):
    Email = models.EmailField()
    Sujet = models.CharField(max_length=255)
    Message = models.TextField()

    def __str__(self):
        return self.email

app_site_cv/etudes/models.py
from django.db import models

# Create your models here.

app_site_cv/experience/models.py
from django.db import models


# Create your models here.
class ExperiencePro(models.Model):
    metier = models.CharField(max_length=150)
    societe = models.CharField(max_length=150)
    contenu = models.TextField()
    slug = models.SlugField(max_length=100)
    date_start = models.DateField()
    date_end = models.DateField()
    image = models.ImageField(default='default.jpg')

    def __str__(self):
        return self.metier

app_site_cv/skills/models.py
from django.db import models


# Create your models here.


class Skills(models.Model):
    titre = models.CharField(max_length=15)
    niveau = models.IntegerField()

    def __str__(self):
        return self.titre

app_site_cv/contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

app_site_cv/experience/forms.py
from django.forms import ModelForm

from .models import ExperiencePro


class ExperienceForm(ModelForm):
    class Meta:
        model = ExperiencePro
        fields = ['metier', 'societe', 'contenu', 'slug', 'date_start', 'date_end', 'image']

app_site_cv/skills/forms.py
from django.forms import ModelForm

from .models import Skills


class SkillsForm(ModelForm):
    class Meta:
        model = Skills
        fields = ['titre', 'niveau']

app_site_cv/contact/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            email_subject = f'New contact {form.cleaned_data["Email"]}: {form.cleaned_data["Sujet"]}'
            email_message = form.cleaned_data['Message']
            send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
            return render(request, 'contact/succes.html')
    form = ContactForm()
    return render(request, 'contact/contact.html', context={'form': form})
# def contact_view(request):
#     form = ContactForm()
#     if request.method == "POST":
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             nom = form.cleaned_data['nom']
#             prenom = form.cleaned_data['prenom']
#             email = form.cleaned_data['email']
#             message = form.cleaned_data['message']
#             titre = f'blog | {nom} {prenom} - {email}'
#             send_mail(titre, message, 'mickael.gerard.site@gmail.com', ['mickael.gerard.site@gmail.com'])
#         return HttpResponseRedirect(reverse('remerciements'))
#     return render(request, 'contact/contact.html', {"form": form})
#
#
# def remerciements_view(request):
#     return render(request, 'contact/succes.html')

app_site_cv/etudes/views.py
from django.shortcuts import render


def etudes(request):
    return render(request, 'etudes/etudes.html')

app_site_cv/experience/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse

from .forms import ExperienceForm
from .models import ExperiencePro


def experiences_pro(request):
    experiences = ExperiencePro.objects.all()
    return render(request, 'experience/experience.html', context={'experiences': experiences})


def experience_pro(request, slug):
    experience = get_object_or_404(ExperiencePro, slug=slug)
    return render(request, 'experience/detail.html', context={"experience": experience})


def creer_view(request):
    form = ExperienceForm
    if request.method == 'POST':
        form = ExperienceForm(request.POST, request.FILES)
        form.save()
        return HttpResponseRedirect(reverse('experiences:experiences'))
    return render(request, "experience/creer.html", context={'form': form})

app_site_cv/home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')

app_site_cv/skills/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import SkillsForm
from .models import Skills


# from django.shortcuts import get_object_or_404
# from django.http import HttpResponse


def skills(request):
    skills = Skills.objects.all().order_by()
    return render(request, 'skills/skills.html', context={"skills": skills})


def create_skills(request):
    form = SkillsForm
    if request.method == 'POST':
        form = SkillsForm(request.POST, request.FILES)
        form.save()
        return HttpResponseRedirect(reverse('skills:skills'))
    return render(request, "skills/create_skills.html", context={'form': form})

app_site_cv/contact/templates/contact/contact.html
{% extends 'navbar_footer.html' %}

{% block titre %}Contact{% endblock %}

{% block contenu %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h1>Contactez moi</h1>
            <form action="#" class="col-3" method="POST">
                <div class="col-12 mt-4 mb-4 fs-4">
                    {% csrf_token %}
                    {{ form }}
                    <div class="col-12 mt-3">
                        <button class="btn btn-danger" type="submit">Envoyer</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app_site_cv/contact/templates/contact/succes.html
{% extends 'navbar_footer.html' %}

{% load static %}

{% block titre %}Contact{% endblock %}

{% block contenu %}

<div class="container dd-flex align-items-center min-vh-100 mt-xxl-5">
    <div class="alert alert-dismissible alert-warning text-center">
        <h4 class="alert-heading justify-content-center">Vous avez réussi!</h4>
        <p class="mb-0">Votre email est envoyé <a class="alert-link" href="#">avec succès</a>.</p>
        <a class="btn btn-outline-success btn-lg mt-4" href="{% url 'experiences:experiences' %}" role="button">Retour
            expérience</a>
    </div>
</div>

{% endblock %}

app_site_cv/etudes/templates/etudes/etudes.html
{% extends 'navbar_footer.html' %}

{% load static %}

{% block titre %} Formations {% endblock %}

{% block contenu %}

<div class="container mt-5" style="height: 700px">
    <div class="row">
        <ul class="list-group col-6">
            <li class="list-group-item text-center fs-3">Formations</li>
            <li class="list-group-item list-group-item-primary">
                <p class="text-decoration-underline fs-4">Titre RNCP Développeur IA :</p>
                <p class="fw-bold fs-5">Ecole IA Microsoft by Simplon</p>
            </li>
            <li class="list-group-item list-group-item-secondary">
                <p class="text-decoration-underline fs-4">Licence en logistique et commercialisation des boissons</p>
                <p class="fw-bold fs-5">DISTECH, ICN Nancy</p>
            </li>
            <li class="list-group-item list-group-item-success">
                <p class="text-decoration-underline fs-4">BTS électronique</p>
                <p class="fw-bold fs-5">ESR Nancy</p>
            </li>
            <li class="list-group-item list-group-item-danger">
                <p class="text-decoration-underline fs-4">Bac électronique</p>
                <p class="fw-bold fs-5">Loritz Nancy</p>
            </li>

        </ul>
        <ul class="list-group col-6 text-center">
            <li class="list-group-item text-center fs-3">Année obtention diplôme</li>
            <li class="list-group-item list-group-item-primary fs-4" style="height: 115px">2021</li>
            <li class="list-group-item list-group-item-secondary fs-4" style="height: 115px">2004</li>
            <li class="list-group-item list-group-item-success fs-4" style="height: 115px">2001</li>
            <li class="list-group-item list-group-item-danger fs-4" style="height: 115px">1998</li>
        </ul>
    </div>

</div>


{% endblock %}

app_site_cv/experience/templates/experience/creer.html
{% extends 'navbar_footer.html' %}

{% block contenu %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h1>Nouvel exp</h1>
            <hr class="my-4">
            <form action="{% url 'experiences:creer' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-danger" type="submit">Créer</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_site_cv/experience/templates/experience/detail.html
{% extends 'navbar_footer.html' %}

{% block contenu %}
<div class="container d-flex align-items-center justify-content-center" style="height: 850px">
    <div class="card">
        <div class="row">
            <h5 class="card-header col-6 text-center text-info fs-2">{{ experience.metier }}</h5>
            <h5 class="card-header col-6 text-center text-warning fs-2">{{ experience.societe }}</h5>
        </div>
        <div class="card-body">
            <h5 class="card-title text-center mb-4 fw-bold text-decoration-underline">Du {{experience.date_start}} au {{experience.date_end}}</h5>
            <p class="card-text fs-3">{{experience.contenu}}</p>
            <a class="btn btn btn-outline-light" href="{% url 'experiences:experiences' %}" >Retour expériences</a>
        </div>
    </div>
</div>
{% endblock %}

app_site_cv/experience/templates/experience/experience.html
{% extends 'navbar_footer.html' %}

{% block titre %}Mes expériences{% endblock %}

{% block contenu %}

<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6 text-lg-start">
            <h1>Mes expériences</h1>
        </div>
        <!--<div class="col-lg-6 text-lg-end">
            <a class="btn btn-black" href="{% url 'experiences:creer' %}">Ajouter une nouvelle expérience</a>
        </div>-->
    </div>
</div>

<hr class="my-4">

<div class="container"  style="width: 50%">
    {% for experience in experiences %}
    <div class="card mb-4">
        <div class="row">
            <h5 class="card-header col-6 text-center text-info fs-2">{{ experience.metier }}</h5>
            <h5 class="card-header col-6 text-center text-warning fs-2">{{ experience.societe }}</h5>
        </div>
        <div class="card-body d-inline-block text-truncate">
            <h5 class="card-title text-center mb-4 fw-bold text-decoration-underline">Du {{experience.date_start}} au {{experience.date_end}}</h5>
            <p class="card-text fs-3">{{experience.contenu}}</p>
            <a class="btn btn btn-outline-light" href="{% url 'experiences:experience' slug=experience.slug %}">...</a>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

app_site_cv/home/templates/home/home.html
{% extends 'navbar_footer.html' %}

{% load static %}

{% block titre %} Présentation {% endblock %}

{% block contenu %}

<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Qui suis je ?</h1>
        <p class="lead">Après 15 ans d'expérience en force de vente essentiellement acquise en Café, Hôtel,
            Restaurant (CHR). Ce qui m'a permis d'acquérir une forte expérience en relation client, un sens
            développé du contact client et d'une pugnacité à toute épreuve. J'ai décidé de me reconvertir dans
            l'informatique.</p>
        <hr class="my-4">
        <p> J'ai donc décidé de suivre une formation Microsoft by Simplon pour devenir développeur Intelligence
            Artificielle. Passionné d’informatique depuis ma tendre enfance, j’ai décidé de changer totalement de métier
            pour
            revenir à mon premier amour, l’informatique. Mon appétence pour chercher le point-virgule qui s’est
            méchamment inséré à la place de la virgule dans un code de 500 lignes, fait de moi un professionnel
            consciencieux ayant une motivation à toute épreuve.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'experiences:experiences' %}" role="button">Expériences</a>
        </p>
    </div>
</div>

<hr class="my-4">

<div class="container">
    <div class="row">
        <div class="col-lg mb-4">
            <img alt="Image de blog" class="w-75" src="{% get_media_prefix %}anatomy.png">
        </div>
        <div class="col-lg text-justify">
            <h1>En résumé</h1>
            <hr class="my-3">
            <p class="lead">
            <ul>
                <li class="display-6">
                    Développeur IA Nancyclotep CHRU de Nancy Brabois
                </li>
                <li class="display-6 mt-3">
                    Commercial Transgourmet Ludres
                </li>
                <li class="display-6 mt-3">
                    Chargé de recouvrement Franfinance Nancy
                </li>
            </ul>
            </p>
        </div>
    </div>
</div>


{% endblock %}

app_site_cv/skills/templates/skills/create_skills.html
{% extends 'navbar_footer.html' %}

{% block contenu %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h1>Ajouter de nouveau skills</h1>
            <hr class="my-4">
            <form action="{% url 'skills:create_skills' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-danger" type="submit">Créer skills</button>
        </div>
    </div>
    </form>
</div>
{% endblock %}

app_site_cv/skills/templates/skills/skills.html
{% extends 'navbar_footer.html' %}

{% load static %}

{% block titre %} Skills {% endblock %}

{% block contenu %}

<div class="container">
    <h2 class="text-center mt-4">Soft skills</h2>
    <hr class="mb-4">
    <div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="3" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="4" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="5" data-target="#carouselExampleIndicators"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active text-center">
                <p class="text-white display-4">Autonome</p>
            </div>
            <div class="carousel-item text-center">
                <p class="text-white display-4">Esprit d'équipe</p>
            </div>
            <div class="carousel-item text-center">
                <p class="text-white display-4">Capacité d'adaptation</p>
            </div>
            <div class="carousel-item text-center">
                <p class="text-white display-4">Pugnace</p>
            </div>
            <div class="carousel-item text-center">
                <p class="text-white display-4">Gestion du stress</p>
            </div>
            <div class="carousel-item text-center">
                <p class="text-white display-4">Adaptabilité</p>
            </div>
        </div>
        <hr class="mb-4">
    </div>
</div>

<div class="container ">
    <div class="row">
        <div class="col-6">
            <h2 class="text-center mt-4">Skills</h2>
        </div>
        <!--<div class="col-6 text-lg-center mt-4">
            <a class="btn btn-dark" href="{% url 'skills:create_skills' %}">Ajouter un nouveau skill</a>
        </div>-->
    </div>
    <hr>
    {% for skill in skills %}
    <p class="text-primary">{{ skill.titre }}</p>
    <div class="progress mb-4" style="height: 20px;">
        <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" class="progress-bar bg-info"
             role="progressbar" style="width:{{skill.niveau}}%;">
            {{skill.niveau}}%
        </div>
    </div>
    {% endfor %}
</div>


<div class="container">
    <h2 class="text-center mt-4">Intérêts</h2>
    <hr class="mb-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black">
                    <i class="fa-solid fa-circle fa-stack-2x"></i>
                    <i class="fas fa-book-skull fa-stack-1x fa-inverse"></i>
                </span>
                <h2 class="display-6">Manga</h2>
            </div>

            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black;">
                    <i class="fa-solid fa-circle fa-stack-2x fa-inverse"></i>
                    <i class="fa-brands fa-old-republic fa-stack-1x"></i>
                </span>
                <h2 class="display-6">Politique</h2>
            </div>

            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black;">
                    <i class="fa-solid fa-circle fa-stack-2x fa-inverse"></i>
                    <i class="fa-solid fa-clapperboard fa-stack-1x"></i>
                </span>
                <h2 class="display-6">Cinéma</h2>
            </div>

            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black;">
                    <i class="fa-solid fa-circle fa-stack-2x fa-inverse"></i>
                    <i class="fa-solid fa-gamepad fa-stack-1x"></i>
                </span>
                <h2 class="display-6">Jeux vidéo</h2>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black;">
                    <i class="fa-solid fa-circle fa-stack-2x fa-inverse"></i>
                    <i class="fa-solid fa-book-open-reader fa-stack-1x"></i>
                </span>
                <h2 class="display-6">Lecture</h2>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <span class="fa-stack fa-3x" style="--fa-inverse: black;">
                    <i class="fa-solid fa-circle fa-stack-2x fa-inverse"></i>
                    <i class="fa-solid fa-plane-departure fa-stack-1x"></i>
                </span>
                <h2 class="display-6">farniente</h2>
            </div>


        </div>
    </div>

</div>

{% endblock %}

app_site_cv/templates/home.html
{% extends 'navbar_footer.html' %}

{% block titre %} Présentation {% endblock %}

{% block contenu %}

<h1>Wjxkjxkjxkj</h1>

{% endblock %}

app_site_cv/templates/navbar_footer.html
<!DOCTYPE html>

{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block titre %} {% endblock %}</title>
    <!-- CSS only -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrit
          rel="stylesheet" y="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3">
    <!--    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- reference your installed Font Awesome Free package's files here -->
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=Indie+Flower&display=swap" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
    <div class="container-fluid">
        <a class="navbar-brand fs-3" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">Gérard
            Mickaël</a>
        <button aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarColor02" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-lg-center" id="navbarColor02">
            <ul class="navbar-nav fs-5">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Présentation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'experiences:experiences' %}">Expériences professionnelles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'skills:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'etudes:etudes' %}">Formations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
                </li>
        </div>
    </div>

</nav>
{% block contenu %} {% endblock %}

<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">

            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/gerard-mickael/"
               role="button" target="_blank">
                <i class="fab fa-linkedin-in"></i
                ></a>

            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/micka-sudo"
               role="button" target="_blank">
                <i class="fab fa-github"></i
                ></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        &copy; 2022 Copyright : Gérard Mickaël
    </div>
    <!-- Copyright -->
</footer>


<!-- JavaScript Bundle with Popper -->
<script crossorigin="anonymous"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>